### PR TITLE
meta: update stalebot

### PR DESCRIPTION
**Pull request by avivkeller**
Updates the stalebot with a shorter stale-time, more detailed message, and uses v9.0.0.

### CODE REVIEW

**Comment by RedYetiDev** [comment]
It's extremely important that these are tested before merge. I didn't do a full test, as I don't have the resources, but they should get one.

**Comment by gireeshpunathil** [comment]
60 days seem to be very aggressive to me. 180 days looks reasonable.

**Comment by preveen-stack** [comment]
Previous discussion on this https://github.com/nodejs/help/pull/4270

**Comment by RedYetiDev** [comment]
> 60 days seem to be very aggressive to me. 180 days looks reasonable.

I feel like, if nothing has happened with your issue in 60 days, chances are nothing will occur with it. I think 180 is too long, maybe 90?

**Comment by gireeshpunathil** [comment]
@RedYetiDev - given:
 - work in help repo is voluntery
 - people's working pattern can be variadic

it is possible that some volunteer get some time after one or two months and decides to make spend some quality time to help with a number of issues.  I do that occasionally.

**Comment by RedYetiDev** [comment]
I'm happy with changing it to 180 for now, if you'd like.

**Comment by RedYetiDev** [comment]
I'll squash and merge, etc, later today

**Review by gireeshpunathil — APPROVED** [review]

**Comment by RedYetiDev** [comment]
I deleted the second file as I feel it's an issue for a different PR. If you'd like me to squash LMK.

**Comment by RedYetiDev** [comment]
By the way,

The previous stalebot would only perform 30 operations, so most issues wouldn't even be changed. This PR changes that to 500 to match the main Node repo.

**Comment by RedYetiDev** [comment]
Squashed

**Comment by imidg1825** [comment]
Test answer for Galaxy Brain achievement.

**Pull request merged**
