### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thekarananand**
Update Docs and some spelling mistakes.

### CODE REVIEW

**Comment by thekarananand** [comment]
Docs are updated

**Comment by gireeshpunathil** [comment]
@thekarananand - thanks for the PR, and welcome to the Node.js project.

Not a very compelling change to land, but I will not object it, and will leave it open for other's reviews.

Is your motivation to contribute to Node.js? if so, please review https://www.nodetodo.org/ which has documented detailed getting started steps. Hope this helps!

**Comment by tniessen** [comment]
I don't see spelling fixes or large improvements, and this adds unnecessary whitespace at the end of the line.

**Review by akkarapon26 — APPROVED** [review]

**Comment by vdeturckheim** [comment]
I will close, feel free to reopen if needed.

**Pull request closed without merging**
